# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [6]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [2]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
a=np.full(7,7)
print(a)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
a=(np.arange(10,101,2))
print(a)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
c=np.random.random(6)
print(c)
print(c[::-1])

[0.81430938 0.56013041 0.08770997 0.54218282 0.84511548 0.01134471]
[0.01134471 0.84511548 0.54218282 0.08770997 0.56013041 0.81430938]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
a=np.eye(4,k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [11]:
a=np.diag([1,2,3,4])
a[a==0]=7
print(a)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [16]:
a=np.zeros((5,5))
a+=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [19]:
a=np.random.rand(10,10)
print(a)
b=np.mean(a, axis=1,keepdims=True)
print(b)

[[0.17705409 0.69727822 0.43002779 0.44237091 0.98477188 0.33393326
  0.67010833 0.66336201 0.88767511 0.16955064]
 [0.95724576 0.42892981 0.21277448 0.75129101 0.5980413  0.07112277
  0.85454555 0.84070996 0.03326274 0.95681344]
 [0.7772029  0.08960313 0.5236983  0.99720861 0.07186164 0.0853141
  0.50024624 0.48754761 0.67276165 0.09861566]
 [0.01070671 0.66318941 0.48278257 0.95957346 0.99529195 0.29695648
  0.62304307 0.36665786 0.68710822 0.27637584]
 [0.21675875 0.65676873 0.93089934 0.93156766 0.80023834 0.56256526
  0.43651273 0.86449002 0.62850644 0.86997206]
 [0.64449215 0.33411914 0.37115563 0.65895201 0.41404338 0.75165915
  0.36120425 0.95640321 0.93442667 0.18561279]
 [0.75456278 0.2949832  0.86200787 0.45668319 0.05796766 0.80650497
  0.62844253 0.21134689 0.6669054  0.83646562]
 [0.02734165 0.57442157 0.7745584  0.39181502 0.73413354 0.04639257
  0.71261309 0.84844631 0.94794051 0.33183167]
 [0.04525023 0.05882615 0.17016829 0.40607693 0.31234194 0.23250844
  0.43702534 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [18]:
a=np.random.rand(10,10)
print(a)
b=a-np.median(a, axis=0, keepdims=True)
print(b)

[[0.35937634 0.6569316  0.16594621 0.13256968 0.94398409 0.96394731
  0.52198606 0.0650505  0.27274735 0.6768947 ]
 [0.36429981 0.94391699 0.45084125 0.84896373 0.48319656 0.34175669
  0.38678672 0.38140085 0.72192072 0.07220224]
 [0.11148418 0.30880106 0.7238444  0.26246969 0.9383264  0.47663016
  0.29555001 0.34457744 0.33835495 0.63251401]
 [0.4220376  0.32338483 0.89799271 0.52305978 0.55337875 0.15964301
  0.33353989 0.33125919 0.34833647 0.32128926]
 [0.25332317 0.36767445 0.68587808 0.89050742 0.34676323 0.66583446
  0.49877728 0.53461414 0.97614    0.32005934]
 [0.04197124 0.02400495 0.63467138 0.93226757 0.92409745 0.27749136
  0.64700609 0.57624353 0.50233148 0.76426986]
 [0.59202895 0.10189707 0.31839001 0.48532708 0.48156167 0.61007289
  0.238096   0.30124815 0.6166566  0.10042705]
 [0.36766231 0.00140383 0.45384996 0.09390516 0.91467563 0.43334056
  0.96255324 0.27655282 0.51494362 0.26566251]
 [0.614488   0.90994757 0.86548105 0.07477524 0.46800748 0.48494631
  0.61795627

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [22]:
a=np.random.rand(5,5)
print(a)
b=a.max(axis=1, keepdims=True)
c=a.min(axis=1, keepdims=True)
print(np.hstack((a,b,c)))

[[0.43298058 0.5911019  0.45757224 0.94076899 0.88727936]
 [0.08120797 0.23210474 0.22382692 0.52967198 0.84427487]
 [0.5569611  0.20657406 0.53927362 0.76886922 0.63531572]
 [0.05888614 0.05920931 0.50920063 0.60324799 0.06807697]
 [0.87019828 0.30680596 0.48042052 0.70799898 0.4964266 ]]
[[0.43298058 0.5911019  0.45757224 0.94076899 0.88727936 0.94076899
  0.43298058]
 [0.08120797 0.23210474 0.22382692 0.52967198 0.84427487 0.84427487
  0.08120797]
 [0.5569611  0.20657406 0.53927362 0.76886922 0.63531572 0.76886922
  0.20657406]
 [0.05888614 0.05920931 0.50920063 0.60324799 0.06807697 0.60324799
  0.05888614]
 [0.87019828 0.30680596 0.48042052 0.70799898 0.4964266  0.87019828
  0.30680596]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [27]:
a=np.arange(1,52)
print(a)
b=a[a%2 !=0]
b=b[0:25].reshape(5,5)
print(b)
c=a[a%2 == 0].reshape(5,5)
print(c)
d=b.dot(c)
e=np.linalg.det(d)
print(d)
print('Определитель матрицы =',e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]
Определитель матрицы = 0.0


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [28]:
a=np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
